In [4]:
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)

In [5]:
!pip install langchain langchain-community langchain-openai

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.0)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.1)
Requirement already satisfied: langchain-openai in /usr/local/lib/python3.12/dist-packages (1.1.7)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.7)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.1)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.45)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.59)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: openai<3.0.0,>=1.109.1 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (2.12.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.12.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.0)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.12.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (0.12.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.67.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2025.11.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2025.11.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)

In [6]:
import os
os.environ["OPENAI_API_KEY"] = "sk-or-v17"
os.environ["OPENAI_API_BASE"] = "https://openrouter.ai/api/v1"

In [7]:
import os
import pandas as pd

In [ ]:
from google_play_scraper import reviews, Sort

APP_ID = "com.application.zomato"

result, _ = reviews(
    APP_ID,
    lang='en',
    country='in',
    sort=Sort.NEWEST,
    count=50
)

for r in result:
    print(f"Date: {r.get('at')}")
    print(f"Rating: {r.get('score')}")
    print(f"Review: {r.get('content')}")
    print("-" * 10)

Date: 2026-01-09 09:46:31
Rating: 5
Review: excellent
----------
Date: 2026-01-09 09:46:28
Rating: 5
Review: zomato is a very good app for food lover...service also very good...
----------
Date: 2026-01-09 09:46:01
Rating: 4
Review: express delivery
----------
Date: 2026-01-09 09:45:31
Rating: 5
Review: A low-priced, simple UI.
----------
Date: 2026-01-09 09:44:41
Rating: 5
Review: nice app
----------
Date: 2026-01-09 09:43:59
Rating: 5
Review: good
----------
Date: 2026-01-09 09:42:36
Rating: 5
Review: expensive service and time actually fix
----------
Date: 2026-01-09 09:40:56
Rating: 5
Review: nicee
----------
Date: 2026-01-09 09:39:29
Rating: 5
Review: Great
----------
Date: 2026-01-09 09:37:50
Rating: 4
Review: good
----------
Date: 2026-01-09 09:35:54
Rating: 5
Review: Happy
----------
Date: 2026-01-09 09:35:34
Rating: 5
Review: As per my experience Zomato is very useful for me. Keep updating. Thanks.
----------
Date: 2026-01-09 09:32:23
Rating: 5
Review: good service 👍 we are regularly ordering 😀 our food tq zomato food on time
----------
Date: 2026-01-09 09:32:12
Rating: 5
Review: 👍🙂 Nice
----------
Date: 2026-01-09 09:31:20
Rating: 5
Review: osm
----------
Date: 2026-01-09 09:31:17
Rating: 5
Review: very good 👍😊
----------
Date: 2026-01-09 09:30:53
Rating: 5
Review: superb
----------
Date: 2026-01-09 09:30:18
Rating: 1
Review: bad , don't use this App
----------
Date: 2026-01-09 09:29:13
Rating: 5
Review: good
----------
Date: 2026-01-09 09:25:42
Rating: 1
Review: they are terribly slow and their call center agents are useless.
----------
Date: 2026-01-09 09:25:22
Rating: 5
Review: good
----------
Date: 2026-01-09 09:22:01
Rating: 5
Review: good
----------
Date: 2026-01-09 09:21:05
Rating: 5
Review: very good experience
----------
Date: 2026-01-09 09:19:12
Rating: 3
Review: charging extra with different categories
----------
Date: 2026-01-09 09:17:40
Rating: 4
Review: Good
----------
Date: 2026-01-09 09:17:21
Rating: 4
Review: Order Zomato se kiya gaya tha, par biryani Swiggy ke packets me deliver hui. Yeh galat aur confusing hai. Zomato ko is baat par dhyaan dena chahiye.”
----------
Date: 2026-01-09 09:16:35
Rating: 5
Review: good ❤️
----------
Date: 2026-01-09 09:14:57
Rating: 4
Review: good
----------
Date: 2026-01-09 09:14:09
Rating: 5
Review: time on delivery one delivery man is rude but all is good
----------
Date: 2026-01-09 09:09:59
Rating: 5
Review: very good app
----------
Date: 2026-01-09 09:09:17
Rating: 3
Review: good 👍
----------
Date: 2026-01-09 09:08:46
Rating: 4
Review: but tooo coast of delevery charges 😊
----------
Date: 2026-01-09 09:05:49
Rating: 5
Review: nice 👍👍👍👍
----------
Date: 2026-01-09 09:05:47
Rating: 4
Review: very good prices
----------
Date: 2026-01-09 09:05:23
Rating: 5
Review: nice
----------
Date: 2026-01-09 09:05:09
Rating: 4
Review: on time delivery, thanks zomato.
----------
Date: 2026-01-09 09:04:43
Rating: 5
Review: no extra surge fees
----------
Date: 2026-01-09 09:00:22
Rating: 5
Review: satisfied
----------
Date: 2026-01-09 09:00:20
Rating: 5
Review: good
----------
Date: 2026-01-09 08:59:03
Rating: 5
Review: v good
----------
Date: 2026-01-09 08:58:06
Rating: 5
Review: ok
----------
Date: 2026-01-09 08:57:28
Rating: 5
Review: nice 👍 good food
----------
Date: 2026-01-09 08:56:52
Rating: 5
Review: good
----------
Date: 2026-01-09 08:54:32
Rating: 5
Review: amazing
----------
Date: 2026-01-09 08:51:24
Rating: 5
Review: good service
----------
Date: 2026-01-09 08:50:39
Rating: 5
Review: good
----------
Date: 2026-01-09 08:50:07
Rating: 5
Review: good 👍
----------
Date: 2026-01-09 08:48:13
Rating: 5
Review: best one
----------
Date: 2026-01-09 08:47:02
Rating: 5
Review: nice app
----------
Date: 2026-01-09 08:45:28
Rating: 5
Review: nice for train delivery
----------

In [42]:
df=pd.DataFrame(result)
df['date'] = df['at'].dt.date
df[['date', 'score', 'content']].head()

         date  score                                            content
0  2026-01-09      5                                          excellent
1  2026-01-09      5  zomato is a very good app for food lover...ser...
2  2026-01-09      4                                   express delivery
3  2026-01-09      5                           A low-priced, simple UI.
4  2026-01-09      5                                           nice app

In [43]:
base_path = "data/zomato"
os.makedirs(base_path, exist_ok=True)

In [44]:
for date, daily_df in df.groupby('date'):
    file_path = f"{base_path}/{date}.csv"
    daily_df[['date', 'score', 'content']].to_csv(file_path, index=False)

In [49]:
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

from langchain_openai import ChatOpenAI

model = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
    max_tokens=128
)

In [50]:
df = pd.read_csv("/content/data/zomato/2026-01-08.csv")

sample_review = df.iloc[0]["content"]

print(sample_review)

excellent

In [51]:
prompt = PromptTemplate(template="""
You are analyzing Google Play Store app reviews.

Your task is to extract ALL concrete topics related to:
- specific issues
- specific complaints
- specific requests
- specific suggestions
- specific feedback about features, service, or experience

CRITICAL RULES:
- Topics MUST refer to a concrete aspect (delivery, food, app, support, pricing, etc.)
- Do NOT return generic phrases like:
  "Positive feedback", "Negative feedback", "Good experience", "Bad experience"
- Do NOT summarize sentiment
- Topics must be short, specific phrases (3–6 words)
- Always extract at least one concrete topic
- Multiple topics are allowed

Review:
{review}

Return topics as a bullet list.
""")

In [52]:
chain=prompt | model | StrOutputParser()

response = chain.invoke({
    "review": sample_review
})

print(response)

- No specific topics identified

In [53]:
canonical_topics = set([
    "Delivery issue",
    "Delivery partner rude",
    "Late delivery",
    "Food quality issue",
    "App performance issue",
    "App user interface"
])

In [54]:
canonical_prompt = PromptTemplate(template="""
You are a topic canonicalization agent for app review analysis.

Your task:
Given a newly extracted topic and a list of existing canonical topics,
decide the BEST canonical topic.

Rules:
- Merge aggressively
- If the new topic is even loosely similar to an existing topic, MERGE
- Prefer existing topics over creating new ones
- Canonical topics must be short, neutral, and stable over time
- Avoid synonyms, paraphrases, or stylistic variations

If merging:
- Return the EXACT existing topic name

If creating a new topic:
- Rewrite it into a clean, neutral canonical form

Inputs:
New topic:
{new_topic}

Existing canonical topics:
{existing_topics}

Return ONLY ONE topic name. No explanation.
""")

In [55]:
canonical_chain = canonical_prompt | model | StrOutputParser()

testing with real eg

In [56]:
existing = list(canonical_topics)

response = canonical_chain.invoke({
    "new_topic": "Smooth performance",
    "existing_topics": existing
})

print(response)

App performance issue

In [57]:
response = canonical_chain.invoke({
    "new_topic": "UI design",
    "existing_topics": existing
})

print(response)

App user interface

In [58]:
response = canonical_chain.invoke({
    "new_topic": "Refund not received",
    "existing_topics": existing
})

print(response)

Refund not received

In [59]:
canonical_topics.add(response)

In [60]:
canonical_topics

{'App performance issue',
 'App user interface',
 'Delivery issue',
 'Delivery partner rude',
 'Food quality issue',
 'Late delivery',
 'Refund not received'}

In [61]:
topic_chain = chain

In [62]:
import os

data_dir = "/content/data/zomato"
daily_topic_store = {}

for file in sorted(os.listdir(data_dir)):
    if file.endswith(".csv"):
        date = file.replace(".csv", "")
        print("Processing:", date)

        daily_topic_store[date] = process_daily_reviews(
            csv_path=f"{data_dir}/{file}",
            topic_chain=topic_chain,
            canonical_chain=canonical_chain,
            canonical_topics=canonical_topics
        )

Processing: 2026-01-08

Processing reviews: 100%|██████████| 35/35 [01:40<00:00,  2.88s/it]

Processing: 2026-01-09

Processing reviews: 100%|██████████| 50/50 [01:46<00:00,  2.13s/it]

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [65]:
trend_df = pd.DataFrame(daily_topic_store).fillna(0).astype(int)
trend_df

                                   2026-01-08  2026-01-09
App performance issue                       5           4
No specific suggestions mentioned          82         131
App user interface                         11           8
Delivery issue                              7           7
Late delivery                               3           5
Food quality issue                          7           2
Refund not received                         1           0
Delivery partner rude                       0           1

In [67]:

os.makedirs("output", exist_ok=True)

In [69]:
output_path = "output/zomato_topic_trend_sample.csv"
trend_df.to_csv(output_path)